
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    environment:
      - PORT:8000
      - DATABASE_URL=app/data/database.db
    tty: true
    ports:
      - 8000:8000
    command: ["fastapi", "run", "app/main.py", "--port", "8000", "--reload"]
    develop:
      watch:
        - action: sync
          path: ./app
          target: /code/app
    volumes:
      - sqlite_data:/code/app/data

volumes:
  sqlite_data:
  
